// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Smart_DEF_tank_v01

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_DataScreen
void ui_DataScreen_screen_init(void);
lv_obj_t * ui_DataScreen;
lv_obj_t * ui_CommsPanel;
lv_obj_t * ui_CommsLabel;
lv_obj_t * ui_GSMTextArea;
lv_obj_t * ui_CANTextArea;
lv_obj_t * ui_InputPanel;
lv_obj_t * ui_AnalogInLabel;
lv_obj_t * ui_V1Label;
lv_obj_t * ui_V2Label;
lv_obj_t * ui_PT1000Label;
lv_obj_t * ui_AnalogIn1TextArea;
lv_obj_t * ui_AnalogIn2TextArea;
lv_obj_t * ui_PT1000TextArea;
lv_obj_t * ui_Degrees1Label;
lv_obj_t * ui_OutputPanel;
lv_obj_t * ui_Out124VTextArea;
lv_obj_t * ui_Out224VTextArea;
lv_obj_t * ui_Out324VTextArea;
lv_obj_t * ui_Out424VTextArea;
lv_obj_t * ui_Out24VLabel;
lv_obj_t * ui_BatteryVLabel;
lv_obj_t * ui_BattVTextArea;
lv_obj_t * ui_AnalogOutLabel;
lv_obj_t * ui_AnalogOutTextArea;
lv_obj_t * ui_OutVLabel;
lv_obj_t * ui_BMEPanel;
lv_obj_t * ui_BMETempTextArea;
lv_obj_t * ui_Degrees2Label;
lv_obj_t * ui_BMEPresTextArea;
lv_obj_t * ui_PresLabel;
lv_obj_t * ui_HumLabel;
lv_obj_t * ui_BMEHumTextArea;
lv_obj_t * ui_PumpPanel;
lv_obj_t * ui_PumpLabel;
lv_obj_t * ui_PumpMANTextArea;
lv_obj_t * ui_PumpAUTOTextArea;
lv_obj_t * ui_ErrorPanel;
lv_obj_t * ui_ErrorTextArea;
lv_obj_t * ui_TankPanel;
lv_obj_t * ui_IntTankLabel;
lv_obj_t * ui_ExtTankLabel;
lv_obj_t * ui_IntTankBar;
lv_obj_t * ui_IntTankTextArea;
lv_obj_t * ui_ExtTankBar;
lv_obj_t * ui_ExtTankTextArea;
lv_obj_t * ui_FuelTankLabel1;
lv_obj_t * ui_ExtTankBar1;
lv_obj_t * ui_FuelTankTextArea;
lv_obj_t * ui_BattVLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_DataScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_DataScreen);
}
