// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Smart_DEF_tank_v01

#ifndef _SMART_DEF_TANK_V01_UI_H
#define _SMART_DEF_TANK_V01_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "C:\Users\WillHandley\Documents\Firmware_development\Smart_DEF_Tank\smart-def-tank-slave-v01\managed_components\lvgl__lvgl\lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_DataScreen
void ui_DataScreen_screen_init(void);
extern lv_obj_t * ui_DataScreen;
extern lv_obj_t * ui_CommsPanel;
extern lv_obj_t * ui_CommsLabel;
extern lv_obj_t * ui_GSMTextArea;
extern lv_obj_t * ui_CANTextArea;
extern lv_obj_t * ui_InputPanel;
extern lv_obj_t * ui_AnalogInLabel;
extern lv_obj_t * ui_V1Label;
extern lv_obj_t * ui_V2Label;
extern lv_obj_t * ui_PT1000Label;
extern lv_obj_t * ui_AnalogIn1TextArea;
extern lv_obj_t * ui_AnalogIn2TextArea;
extern lv_obj_t * ui_PT1000TextArea;
extern lv_obj_t * ui_Degrees1Label;
extern lv_obj_t * ui_OutputPanel;
extern lv_obj_t * ui_Out124VTextArea;
extern lv_obj_t * ui_Out224VTextArea;
extern lv_obj_t * ui_Out324VTextArea;
extern lv_obj_t * ui_Out424VTextArea;
extern lv_obj_t * ui_Out24VLabel;
extern lv_obj_t * ui_BatteryVLabel;
extern lv_obj_t * ui_BattVTextArea;
extern lv_obj_t * ui_AnalogOutLabel;
extern lv_obj_t * ui_AnalogOutTextArea;
extern lv_obj_t * ui_OutVLabel;
extern lv_obj_t * ui_BMEPanel;
extern lv_obj_t * ui_BMETempTextArea;
extern lv_obj_t * ui_Degrees2Label;
extern lv_obj_t * ui_BMEPresTextArea;
extern lv_obj_t * ui_PresLabel;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_BMEHumTextArea;
extern lv_obj_t * ui_PumpPanel;
extern lv_obj_t * ui_PumpLabel;
extern lv_obj_t * ui_PumpMANTextArea;
extern lv_obj_t * ui_PumpAUTOTextArea;
extern lv_obj_t * ui_ErrorPanel;
extern lv_obj_t * ui_ErrorTextArea;
extern lv_obj_t * ui_TankPanel;
extern lv_obj_t * ui_IntTankLabel;
extern lv_obj_t * ui_ExtTankLabel;
extern lv_obj_t * ui_IntTankBar;
extern lv_obj_t * ui_IntTankTextArea;
extern lv_obj_t * ui_ExtTankBar;
extern lv_obj_t * ui_ExtTankTextArea;
extern lv_obj_t * ui_FuelTankLabel1;
extern lv_obj_t * ui_ExtTankBar1;
extern lv_obj_t * ui_FuelTankTextArea;
extern lv_obj_t * ui_BattVLabel;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
