// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Auto_DEF_v0.1

#ifndef UI_DATASCREEN_H
#define UI_DATASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DataScreen
extern void ui_DataScreen_screen_init(void);
extern void ui_DataScreen_screen_destroy(void);
extern lv_obj_t * ui_DataScreen;
extern lv_obj_t * ui_CommsPanel;
extern lv_obj_t * ui_CommsLabel;
extern lv_obj_t * ui_GSMTextArea;
extern lv_obj_t * ui_CANTextArea;
extern lv_obj_t * ui_InputPanel;
extern lv_obj_t * ui_PT1000Label;
extern lv_obj_t * ui_PT1000TextArea;
extern lv_obj_t * ui_Degrees1Label;
extern lv_obj_t * ui_OutputPanel;
extern lv_obj_t * ui_Out124VTextArea;
extern lv_obj_t * ui_Out224VTextArea;
extern lv_obj_t * ui_Out24VLabel;
extern lv_obj_t * ui_BatteryVLabel;
extern lv_obj_t * ui_BattVTextArea;
extern lv_obj_t * ui_BMEPanel;
extern lv_obj_t * ui_BMETempTextArea;
extern lv_obj_t * ui_Degrees2Label;
extern lv_obj_t * ui_BMEPresTextArea;
extern lv_obj_t * ui_PresLabel;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_BMEHumTextArea;
extern lv_obj_t * ui_PumpLabel;
extern lv_obj_t * ui_PumpMANTextArea;
extern lv_obj_t * ui_PumpAUTOTextArea;
extern lv_obj_t * ui_ErrorPanel;
extern lv_obj_t * ui_ErrorTextArea;
extern lv_obj_t * ui_TankPanel;
extern lv_obj_t * ui_IntTankLabel;
extern lv_obj_t * ui_ExtTankLabel;
extern lv_obj_t * ui_IntTankBar;
extern lv_obj_t * ui_IntTankTextArea;
extern lv_obj_t * ui_ExtTankBar;
extern lv_obj_t * ui_ExtTankTextArea;
extern lv_obj_t * ui_AuxTankLabel1;
extern lv_obj_t * ui_ExtTankBar1;
extern lv_obj_t * ui_AuxTankTextArea;
extern lv_obj_t * ui_BattVLabel;
extern lv_obj_t * ui_BatteryVLabel1;
extern lv_obj_t * ui_Out1NPNTextArea1;
extern lv_obj_t * ui_Out2NPNTextArea2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

