// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Auto_DEF_v0.1

#include "../ui.h"

lv_obj_t * ui_DataScreen = NULL;
lv_obj_t * ui_CommsPanel = NULL;
lv_obj_t * ui_CommsLabel = NULL;
lv_obj_t * ui_GSMTextArea = NULL;
lv_obj_t * ui_CANTextArea = NULL;
lv_obj_t * ui_InputPanel = NULL;
lv_obj_t * ui_PT1000Label = NULL;
lv_obj_t * ui_PT1000TextArea = NULL;
lv_obj_t * ui_Degrees1Label = NULL;
lv_obj_t * ui_OutputPanel = NULL;
lv_obj_t * ui_Out124VTextArea = NULL;
lv_obj_t * ui_Out224VTextArea = NULL;
lv_obj_t * ui_Out24VLabel = NULL;
lv_obj_t * ui_BatteryVLabel = NULL;
lv_obj_t * ui_BattVTextArea = NULL;
lv_obj_t * ui_BMEPanel = NULL;
lv_obj_t * ui_BMETempTextArea = NULL;
lv_obj_t * ui_Degrees2Label = NULL;
lv_obj_t * ui_BMEPresTextArea = NULL;
lv_obj_t * ui_PresLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_BMEHumTextArea = NULL;
lv_obj_t * ui_PumpLabel = NULL;
lv_obj_t * ui_PumpMANTextArea = NULL;
lv_obj_t * ui_PumpAUTOTextArea = NULL;
lv_obj_t * ui_ErrorPanel = NULL;
lv_obj_t * ui_ErrorTextArea = NULL;
lv_obj_t * ui_TankPanel = NULL;
lv_obj_t * ui_IntTankLabel = NULL;
lv_obj_t * ui_ExtTankLabel = NULL;
lv_obj_t * ui_IntTankBar = NULL;
lv_obj_t * ui_IntTankTextArea = NULL;
lv_obj_t * ui_ExtTankBar = NULL;
lv_obj_t * ui_ExtTankTextArea = NULL;
lv_obj_t * ui_AuxTankLabel1 = NULL;
lv_obj_t * ui_ExtTankBar1 = NULL;
lv_obj_t * ui_AuxTankTextArea = NULL;
lv_obj_t * ui_BattVLabel = NULL;
lv_obj_t * ui_BatteryVLabel1 = NULL;
lv_obj_t * ui_Out1NPNTextArea1 = NULL;
lv_obj_t * ui_Out2NPNTextArea2 = NULL;
// event funtions

// build funtions

void ui_DataScreen_screen_init(void)
{
    ui_DataScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DataScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DataScreen, lv_color_hex(0x002E45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DataScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommsPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_CommsPanel, 100);
    lv_obj_set_height(ui_CommsPanel, 100);
    lv_obj_set_x(ui_CommsPanel, -103);
    lv_obj_set_y(ui_CommsPanel, -67);
    lv_obj_set_align(ui_CommsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CommsPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_CommsPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CommsPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CommsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommsLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_CommsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommsLabel, -104);
    lv_obj_set_y(ui_CommsLabel, -100);
    lv_obj_set_align(ui_CommsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommsLabel, "Comms");
    lv_obj_set_style_text_color(ui_CommsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommsLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSMTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_GSMTextArea, 53);
    lv_obj_set_height(ui_GSMTextArea, 36);
    lv_obj_set_x(ui_GSMTextArea, -127);
    lv_obj_set_y(ui_GSMTextArea, -82);
    lv_obj_set_align(ui_GSMTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_GSMTextArea, "GSM");
    lv_textarea_set_placeholder_text(ui_GSMTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_GSMTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_GSMTextArea, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GSMTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GSMTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GSMTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GSMTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GSMTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CANTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_CANTextArea, 52);
    lv_obj_set_height(ui_CANTextArea, 32);
    lv_obj_set_x(ui_CANTextArea, -81);
    lv_obj_set_y(ui_CANTextArea, -80);
    lv_obj_set_align(ui_CANTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_CANTextArea, "CAN");
    lv_textarea_set_placeholder_text(ui_CANTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_CANTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_CANTextArea, lv_color_hex(0xFF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CANTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CANTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CANTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CANTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CANTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_InputPanel, 100);
    lv_obj_set_height(ui_InputPanel, 49);
    lv_obj_set_x(ui_InputPanel, -103);
    lv_obj_set_y(ui_InputPanel, 91);
    lv_obj_set_align(ui_InputPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InputPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_InputPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InputPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InputPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PT1000Label = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_PT1000Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PT1000Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PT1000Label, -103);
    lv_obj_set_y(ui_PT1000Label, 82);
    lv_obj_set_align(ui_PT1000Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PT1000Label, "PT1000");
    lv_obj_set_style_text_color(ui_PT1000Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PT1000Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PT1000Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PT1000TextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_PT1000TextArea, 53);
    lv_obj_set_height(ui_PT1000TextArea, 36);
    lv_obj_set_x(ui_PT1000TextArea, -115);
    lv_obj_set_y(ui_PT1000TextArea, 101);
    lv_obj_set_align(ui_PT1000TextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PT1000TextArea, "999");
    lv_textarea_set_placeholder_text(ui_PT1000TextArea, "Placeholder...");
    lv_obj_clear_flag(ui_PT1000TextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PT1000TextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PT1000TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PT1000TextArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PT1000TextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PT1000TextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PT1000TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PT1000TextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Degrees1Label = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_Degrees1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Degrees1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Degrees1Label, -88);
    lv_obj_set_y(ui_Degrees1Label, 101);
    lv_obj_set_align(ui_Degrees1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Degrees1Label, "°C");
    lv_obj_set_style_text_color(ui_Degrees1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Degrees1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Degrees1Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutputPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_OutputPanel, 100);
    lv_obj_set_height(ui_OutputPanel, 187);
    lv_obj_set_x(ui_OutputPanel, 4);
    lv_obj_set_y(ui_OutputPanel, 22);
    lv_obj_set_align(ui_OutputPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OutputPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_OutputPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OutputPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OutputPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out124VTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_Out124VTextArea, 70);
    lv_obj_set_height(ui_Out124VTextArea, 32);
    lv_obj_set_x(ui_Out124VTextArea, 7);
    lv_obj_set_y(ui_Out124VTextArea, -32);
    lv_obj_set_align(ui_Out124VTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Out124VTextArea, "OUT 1");
    lv_textarea_set_placeholder_text(ui_Out124VTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_Out124VTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Out124VTextArea, lv_color_hex(0xFF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out124VTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Out124VTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Out124VTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Out124VTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Out124VTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out224VTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_Out224VTextArea, 70);
    lv_obj_set_height(ui_Out224VTextArea, 32);
    lv_obj_set_x(ui_Out224VTextArea, 7);
    lv_obj_set_y(ui_Out224VTextArea, -13);
    lv_obj_set_align(ui_Out224VTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Out224VTextArea, "OUT 2");
    lv_textarea_set_placeholder_text(ui_Out224VTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_Out224VTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Out224VTextArea, lv_color_hex(0xFF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out224VTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Out224VTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Out224VTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Out224VTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Out224VTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out24VLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_Out24VLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Out24VLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Out24VLabel, 3);
    lv_obj_set_y(ui_Out24VLabel, -53);
    lv_obj_set_align(ui_Out24VLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Out24VLabel, "24V Out");
    lv_obj_set_style_text_color(ui_Out24VLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out24VLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Out24VLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryVLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_BatteryVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryVLabel, 4);
    lv_obj_set_y(ui_BatteryVLabel, 64);
    lv_obj_set_align(ui_BatteryVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryVLabel, "Batt Volt");
    lv_obj_set_style_text_color(ui_BatteryVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryVLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryVLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattVTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_BattVTextArea, 65);
    lv_obj_set_height(ui_BattVTextArea, 40);
    lv_obj_set_x(ui_BattVTextArea, -9);
    lv_obj_set_y(ui_BattVTextArea, 92);
    lv_obj_set_align(ui_BattVTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_BattVTextArea, "-  ");
    lv_textarea_set_placeholder_text(ui_BattVTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_BattVTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BattVTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattVTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BattVTextArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BattVTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BattVTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BattVTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BattVTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMEPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_BMEPanel, 100);
    lv_obj_set_height(ui_BMEPanel, 76);
    lv_obj_set_x(ui_BMEPanel, -103);
    lv_obj_set_y(ui_BMEPanel, 25);
    lv_obj_set_align(ui_BMEPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BMEPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_BMEPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BMEPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BMEPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BMEPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMETempTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_BMETempTextArea, 53);
    lv_obj_set_height(ui_BMETempTextArea, 36);
    lv_obj_set_x(ui_BMETempTextArea, -120);
    lv_obj_set_y(ui_BMETempTextArea, 3);
    lv_obj_set_align(ui_BMETempTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_BMETempTextArea, "999");
    lv_textarea_set_placeholder_text(ui_BMETempTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_BMETempTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BMETempTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BMETempTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BMETempTextArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BMETempTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BMETempTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BMETempTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BMETempTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Degrees2Label = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_Degrees2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Degrees2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Degrees2Label, -92);
    lv_obj_set_y(ui_Degrees2Label, 3);
    lv_obj_set_align(ui_Degrees2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Degrees2Label, "°C");
    lv_obj_set_style_text_color(ui_Degrees2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Degrees2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Degrees2Label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Degrees2Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMEPresTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_BMEPresTextArea, 65);
    lv_obj_set_height(ui_BMEPresTextArea, 36);
    lv_obj_set_x(ui_BMEPresTextArea, -127);
    lv_obj_set_y(ui_BMEPresTextArea, 23);
    lv_obj_set_align(ui_BMEPresTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_BMEPresTextArea, "199.9");
    lv_textarea_set_placeholder_text(ui_BMEPresTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_BMEPresTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BMEPresTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BMEPresTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BMEPresTextArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BMEPresTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BMEPresTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BMEPresTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BMEPresTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_PresLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresLabel, -86);
    lv_obj_set_y(ui_PresLabel, 24);
    lv_obj_set_align(ui_PresLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresLabel, "hPa");
    lv_obj_set_style_text_color(ui_PresLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, -84);
    lv_obj_set_y(ui_HumLabel, 47);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "%RH");
    lv_obj_set_style_text_color(ui_HumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BMEHumTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_BMEHumTextArea, 53);
    lv_obj_set_height(ui_BMEHumTextArea, 36);
    lv_obj_set_x(ui_BMEHumTextArea, -120);
    lv_obj_set_y(ui_BMEHumTextArea, 47);
    lv_obj_set_align(ui_BMEHumTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_BMEHumTextArea, "999");
    lv_textarea_set_placeholder_text(ui_BMEHumTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_BMEHumTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_BMEHumTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BMEHumTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BMEHumTextArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BMEHumTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BMEHumTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BMEHumTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BMEHumTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumpLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_PumpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PumpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PumpLabel, -105);
    lv_obj_set_y(ui_PumpLabel, -54);
    lv_obj_set_align(ui_PumpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PumpLabel, "Pump");
    lv_obj_set_style_text_color(ui_PumpLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumpLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PumpLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumpMANTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_PumpMANTextArea, 59);
    lv_obj_set_height(ui_PumpMANTextArea, 28);
    lv_obj_set_x(ui_PumpMANTextArea, -126);
    lv_obj_set_y(ui_PumpMANTextArea, -32);
    lv_obj_set_align(ui_PumpMANTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PumpMANTextArea, "MAN");
    lv_textarea_set_placeholder_text(ui_PumpMANTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_PumpMANTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PumpMANTextArea, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumpMANTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PumpMANTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PumpMANTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumpMANTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumpMANTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumpMANTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PumpAUTOTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_PumpAUTOTextArea, 61);
    lv_obj_set_height(ui_PumpAUTOTextArea, 28);
    lv_obj_set_x(ui_PumpAUTOTextArea, -82);
    lv_obj_set_y(ui_PumpAUTOTextArea, -32);
    lv_obj_set_align(ui_PumpAUTOTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PumpAUTOTextArea, "AUTO");
    lv_textarea_set_placeholder_text(ui_PumpAUTOTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_PumpAUTOTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PumpAUTOTextArea, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PumpAUTOTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PumpAUTOTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PumpAUTOTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PumpAUTOTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PumpAUTOTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PumpAUTOTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrorPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_ErrorPanel, 199);
    lv_obj_set_height(ui_ErrorPanel, 42);
    lv_obj_set_x(ui_ErrorPanel, 53);
    lv_obj_set_y(ui_ErrorPanel, -96);
    lv_obj_set_align(ui_ErrorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ErrorPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_ErrorPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ErrorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ErrorPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ErrorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrorTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_ErrorTextArea, 170);
    lv_obj_set_height(ui_ErrorTextArea, 36);
    lv_obj_set_x(ui_ErrorTextArea, 54);
    lv_obj_set_y(ui_ErrorTextArea, -96);
    lv_obj_set_align(ui_ErrorTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ErrorTextArea, "-");
    lv_textarea_set_placeholder_text(ui_ErrorTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_ErrorTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ErrorTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrorTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ErrorTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ErrorTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ErrorTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ErrorTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ErrorTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TankPanel = lv_obj_create(ui_DataScreen);
    lv_obj_set_width(ui_TankPanel, 91);
    lv_obj_set_height(ui_TankPanel, 187);
    lv_obj_set_x(ui_TankPanel, 107);
    lv_obj_set_y(ui_TankPanel, 22);
    lv_obj_set_align(ui_TankPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TankPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_TankPanel, lv_color_hex(0x002447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TankPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TankPanel, lv_color_hex(0x003F5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TankPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntTankLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_IntTankLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntTankLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntTankLabel, 108);
    lv_obj_set_y(ui_IntTankLabel, -53);
    lv_obj_set_align(ui_IntTankLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntTankLabel, "Int. Tank");
    lv_obj_set_style_text_color(ui_IntTankLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntTankLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntTankLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtTankLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_ExtTankLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExtTankLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExtTankLabel, 108);
    lv_obj_set_y(ui_ExtTankLabel, 5);
    lv_obj_set_align(ui_ExtTankLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExtTankLabel, "Ext. Tank");
    lv_obj_set_style_text_color(ui_ExtTankLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ExtTankLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ExtTankLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntTankBar = lv_bar_create(ui_DataScreen);
    lv_obj_set_width(ui_IntTankBar, 37);
    lv_obj_set_height(ui_IntTankBar, 17);
    lv_obj_set_x(ui_IntTankBar, 89);
    lv_obj_set_y(ui_IntTankBar, -26);
    lv_obj_set_align(ui_IntTankBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IntTankBar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_IntTankTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_IntTankTextArea, 49);
    lv_obj_set_height(ui_IntTankTextArea, 37);
    lv_obj_set_x(ui_IntTankTextArea, 130);
    lv_obj_set_y(ui_IntTankTextArea, -26);
    lv_obj_set_align(ui_IntTankTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_IntTankTextArea, "-");
    lv_textarea_set_placeholder_text(ui_IntTankTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_IntTankTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_IntTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntTankTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IntTankTextArea, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IntTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IntTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IntTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IntTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtTankBar = lv_bar_create(ui_DataScreen);
    lv_obj_set_width(ui_ExtTankBar, 37);
    lv_obj_set_height(ui_ExtTankBar, 17);
    lv_obj_set_x(ui_ExtTankBar, 89);
    lv_obj_set_y(ui_ExtTankBar, 32);
    lv_obj_set_align(ui_ExtTankBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtTankBar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_ExtTankTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_ExtTankTextArea, 49);
    lv_obj_set_height(ui_ExtTankTextArea, 37);
    lv_obj_set_x(ui_ExtTankTextArea, 130);
    lv_obj_set_y(ui_ExtTankTextArea, 32);
    lv_obj_set_align(ui_ExtTankTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ExtTankTextArea, "-");
    lv_textarea_set_placeholder_text(ui_ExtTankTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_ExtTankTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ExtTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ExtTankTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ExtTankTextArea, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExtTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ExtTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ExtTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AuxTankLabel1 = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_AuxTankLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuxTankLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuxTankLabel1, 107);
    lv_obj_set_y(ui_AuxTankLabel1, 64);
    lv_obj_set_align(ui_AuxTankLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AuxTankLabel1, "Aux Tank");
    lv_obj_set_style_text_color(ui_AuxTankLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AuxTankLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AuxTankLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExtTankBar1 = lv_bar_create(ui_DataScreen);
    lv_obj_set_width(ui_ExtTankBar1, 37);
    lv_obj_set_height(ui_ExtTankBar1, 17);
    lv_obj_set_x(ui_ExtTankBar1, 89);
    lv_obj_set_y(ui_ExtTankBar1, 90);
    lv_obj_set_align(ui_ExtTankBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtTankBar1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    lv_obj_set_style_bg_color(ui_ExtTankBar1, lv_color_hex(0xAFA504), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExtTankBar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AuxTankTextArea = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_AuxTankTextArea, 49);
    lv_obj_set_height(ui_AuxTankTextArea, 37);
    lv_obj_set_x(ui_AuxTankTextArea, 130);
    lv_obj_set_y(ui_AuxTankTextArea, 90);
    lv_obj_set_align(ui_AuxTankTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_AuxTankTextArea, "-");
    lv_textarea_set_placeholder_text(ui_AuxTankTextArea, "Placeholder...");
    lv_obj_clear_flag(ui_AuxTankTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AuxTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AuxTankTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AuxTankTextArea, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AuxTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AuxTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AuxTankTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AuxTankTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattVLabel = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_BattVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattVLabel, 21);
    lv_obj_set_y(ui_BattVLabel, 90);
    lv_obj_set_align(ui_BattVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BattVLabel, "V");
    lv_obj_set_style_text_color(ui_BattVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattVLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BattVLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryVLabel1 = lv_label_create(ui_DataScreen);
    lv_obj_set_width(ui_BatteryVLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryVLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryVLabel1, 4);
    lv_obj_set_y(ui_BatteryVLabel1, 5);
    lv_obj_set_align(ui_BatteryVLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryVLabel1, "NPN Out");
    lv_obj_set_style_text_color(ui_BatteryVLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryVLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryVLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out1NPNTextArea1 = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_Out1NPNTextArea1, 70);
    lv_obj_set_height(ui_Out1NPNTextArea1, 32);
    lv_obj_set_x(ui_Out1NPNTextArea1, 9);
    lv_obj_set_y(ui_Out1NPNTextArea1, 25);
    lv_obj_set_align(ui_Out1NPNTextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Out1NPNTextArea1, "OUT 1");
    lv_textarea_set_placeholder_text(ui_Out1NPNTextArea1, "Placeholder...");
    lv_obj_clear_flag(ui_Out1NPNTextArea1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Out1NPNTextArea1, lv_color_hex(0xFF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out1NPNTextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Out1NPNTextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Out1NPNTextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Out1NPNTextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Out1NPNTextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Out2NPNTextArea2 = lv_textarea_create(ui_DataScreen);
    lv_obj_set_width(ui_Out2NPNTextArea2, 70);
    lv_obj_set_height(ui_Out2NPNTextArea2, 32);
    lv_obj_set_x(ui_Out2NPNTextArea2, 9);
    lv_obj_set_y(ui_Out2NPNTextArea2, 44);
    lv_obj_set_align(ui_Out2NPNTextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Out2NPNTextArea2, "OUT 2");
    lv_textarea_set_placeholder_text(ui_Out2NPNTextArea2, "Placeholder...");
    lv_obj_clear_flag(ui_Out2NPNTextArea2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Out2NPNTextArea2, lv_color_hex(0xFF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Out2NPNTextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Out2NPNTextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Out2NPNTextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Out2NPNTextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Out2NPNTextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DataScreen_screen_destroy(void)
{
    if(ui_DataScreen) lv_obj_del(ui_DataScreen);

    // NULL screen variables
    ui_DataScreen = NULL;
    ui_CommsPanel = NULL;
    ui_CommsLabel = NULL;
    ui_GSMTextArea = NULL;
    ui_CANTextArea = NULL;
    ui_InputPanel = NULL;
    ui_PT1000Label = NULL;
    ui_PT1000TextArea = NULL;
    ui_Degrees1Label = NULL;
    ui_OutputPanel = NULL;
    ui_Out124VTextArea = NULL;
    ui_Out224VTextArea = NULL;
    ui_Out24VLabel = NULL;
    ui_BatteryVLabel = NULL;
    ui_BattVTextArea = NULL;
    ui_BMEPanel = NULL;
    ui_BMETempTextArea = NULL;
    ui_Degrees2Label = NULL;
    ui_BMEPresTextArea = NULL;
    ui_PresLabel = NULL;
    ui_HumLabel = NULL;
    ui_BMEHumTextArea = NULL;
    ui_PumpLabel = NULL;
    ui_PumpMANTextArea = NULL;
    ui_PumpAUTOTextArea = NULL;
    ui_ErrorPanel = NULL;
    ui_ErrorTextArea = NULL;
    ui_TankPanel = NULL;
    ui_IntTankLabel = NULL;
    ui_ExtTankLabel = NULL;
    ui_IntTankBar = NULL;
    ui_IntTankTextArea = NULL;
    ui_ExtTankBar = NULL;
    ui_ExtTankTextArea = NULL;
    ui_AuxTankLabel1 = NULL;
    ui_ExtTankBar1 = NULL;
    ui_AuxTankTextArea = NULL;
    ui_BattVLabel = NULL;
    ui_BatteryVLabel1 = NULL;
    ui_Out1NPNTextArea1 = NULL;
    ui_Out2NPNTextArea2 = NULL;

}
