// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Auto_DEF_v0.1

#include "../ui.h"

lv_obj_t * ui_SplashScreen = NULL;
lv_obj_t * ui_DFSLogo = NULL;
// event funtions


// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DFSLogo = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_DFSLogo, &ui_img_dfs_logo_png_png);
    lv_obj_set_width(ui_DFSLogo, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_DFSLogo, LV_SIZE_CONTENT);    /// 279
    lv_obj_set_x(ui_DFSLogo, 3);
    lv_obj_set_y(ui_DFSLogo, -16);
    lv_obj_set_align(ui_DFSLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DFSLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DFSLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_DFSLogo, 75);

    

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    ui_DFSLogo = NULL;

}
